parabola: parabola.c 
	cc -o parabola parabola.c -lm

factorial: factorial.c
	cc -o factorial factorial.c 

fibonacci: fibonacci.c 
	cc -o fibonacci fibonacci.c 

heron: heron.c 
	cc -o heron heron.c 

clean:
	rm -f parabola 
	rm -f factorial 
	rm -f fibonacci